generic-service:
  nameOverride: migration-link-exchange-ui
  productId: 'DPS091' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "migration-link-exchange-ui"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/migration-link-exchange-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: migration-link-exchange-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'DPS091' # Your audit service name
    MIGRATION_LINK_EXCHANGE_API_URL: "http://migration-link-exchange-api" # Internal URL of API service
    # See Azure Setup for more information on how to get these values.
    # The following ID is not private, it forms part of the publicly visible oauth login url.
    OAUTH_TENANT_ID: c6874728-71e6-41fe-a9e1-2e8c36776ad8

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    migration-link-exchange-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'
    # Manually created secret.
    auth-session:
      OAUTH_CLIENT_SECRET: OAUTH_CLIENT_SECRET

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: migration-link-exchange-ui
