services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: migration-link-exchange-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    image: ghcr.io/ministryofjustice/migration-link-exchange-api:${APP_VERSION:-latest}
    build:
      context: ../
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/api:8080/health/ping"]
      interval: 5s
      retries: 100
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_ENDPOINT: postgres:5432
      DB_NAME: migration-link-exchange-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  ui:
    image: ghcr.io/ministryofjustice/migration-link-exchange-ui:${APP_VERSION:-latest}
    depends_on:
      - api
    build:
      context: ../
      target: production
    ports:
      - "3000:3000"
    environment:
      PRODUCT_ID: GOOGLE_MIGRATION # TODO: Probably need a PRODUCT_ID
      INGRESS_URL: 'http://localhost:3000'
      MIGRATION_LINK_EXCHANGE_API_URL: 'http://api:8080'
