---
# Per environment values which override defaults in migration-link-exchange-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: migration-link-exchange-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://migration-link-exchange.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PROD
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: N/A
