---
# Per environment values which override defaults in migration-link-exchange-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: find-google-file.service.justice.gov.uk

  env:
    INGRESS_URL: "https://find-google-file.service.justice.gov.uk"
    ENVIRONMENT_NAME: PROD
    AUDIT_ENABLED: "false"
    # See Azure Setup for more information on how to get these values.
    # The following ID is not private, it forms part of the publicly visible oauth login url.
    OAUTH_CLIENT_ID: "5995e47b-365d-43cb-a715-28448ad0c3a4"

generic-prometheus-alerts:
  alertSeverity: N/A
